### ISSUE TITLE
Produce a file for deleted resources

### ISSUE THREAD

**Issue by sunshineo** [awslabs/cdk8s#546]
To remove resource using kubectl we need the file with all the resources deleted and run `kubectl delete -f deleted-resource.yaml`

Our current workaround now is comment out everything else from the main.ts file, run synth to get that file

The other way is save the yaml file in dist folder, delete in main.ts, run synth, then diff the file to get what was deleted

Is it possible to have a diff/deleted command to produce the file automatically?

**Comment by eladb** [comment]
It won't be possible for CDK8s to _know_ which resources are deleted because your CDK app only defines the desired state.

The best practice is to add a label to all resources in your app and then use `kubectl apply --prune` with that label. 
See https://github.com/awslabs/cdk8s/issues/178#issuecomment-792228327 for some details on how to achieve this manually.

@sunshineo let me know if this addresses your requirement so I can close this issue.

**Comment by sunshineo** [comment]
Thank you @eladb . I think we can close this issue
